resolver: ghc-9.2
packages:
  - .
  - sandbox
extra-deps:
  - extra-1.7.8
  - clock-0.8
  - split-0.2.3.4
  - kan-extensions-5.2.3
  - comonad-5.0.8
  - contravariant-1.5.5
  - distributive-0.6.2.1
  - free-5.1.7
  - invariant-0.5.5
  - profunctors-5.6.2
  - semigroupoids-5.3.7
  - tagged-0.8.6.1
  - transformers-compat-0.7.1
  - StateVar-1.2.2
  - adjunctions-4.4
  - base-orphans-0.8.6
  - bifunctors-5.5.11
  - hashable-1.4.0.2
  - indexed-traversable-0.1.2
  - th-abstraction-0.4.3.0
  - transformers-base-0.4.6
  - unordered-containers-0.2.18.0
  - semigroups-0.20
  - void-0.7.3
ghc-options :
  "$everything": -Wall
allow-newer: true
