resolver: ghc-9.2
packages:
  - .
  - sandbox
extra-deps:
  - extra-1.7.8
  - clock-0.8
  - split-0.2.3.4
ghc-options :
  "$everything": -Wall
allow-newer: true
compiler: ghc-git-1370eda7a53f5dfc88afe705b2ffecb1d5544ec7-quickest
